---
- name: down 
  shell: "docker-compose -f {{ monitor_dir }}/docker-compose.yml down"
  ignore_errors: yes
  become: yes
  become_method: sudo
  tags: 
    - down

- name: check monitor dir
  stat:
    path: "{{ monitor_dir }}"
  register: file_status
  tags: 
    - config
- name: create monitor dir
  file:
    path: "{{ monitor_dir }}"
    state: directory
  when:
    file_status.stat.exists == False
  tags: 
    - config

- name: copy docker-compose.yml
  copy:
    src: ../monitor/docker-compose.yml
    dest: "{{ monitor_dir }}/docker-compose.yml"
    mode: 0755
  tags: 
    - config

- name: copy config
  copy:
    src: ../monitor/config
    dest: "{{ monitor_dir }}"
    mode: 0755
  tags: 
    - config

- name: set node exporter ip:port
  shell: sh init_config.sh "{{ monitor_dir }}"
  become: yes
  become_method: sudo
  tags: 
    - config

- name: start 
  shell: "cd {{ monitor_dir }} && docker-compose up -d"
  become: yes
  become_method: sudo
  tags: 
    - start

- name: ensure apm data dirs
  shell: "mkdir -p {{ monitor_dir }}/data/es && mkdir -p {{ monitor_dir }}/data/grafana && mkdir -p {{ monitor_dir }}/data/prometheus"
  become: yes
  become_method: sudo
  tags: 
    - start

- name: chmod apm data
  shell: "chmod 777 {{ monitor_dir }}/data/**"
  become: yes
  become_method: sudo
  tags: 
    - start

- name: clean apm data
  shell: rm -rf  {{ monitor_dir }}/data
  become: yes
  become_method: sudo
  tags: 
    - clean
