name: Cargo Clippy
concurrency:
  group: Cargo Clippy-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: lyricwulf/abc@v1
        with: 
          linux: m4
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy

      - name: cargo-clippy
        run: make clippy && git diff --exit-code Cargo.lock

