name: Unit Tests
concurrency:
  group: Unit Tests-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: lyricwulf/abc@v1
      #   with: 
      #     linux: m4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.59

      - uses: Swatinem/rust-cache@v1
      
      # - name: Init submodules
      #   uses: srt32/git-actions@v0.0.3
      #   with:
      #     args: git submodule update -r --init

      # - name: Install moleculec
      #   run: cargo install moleculec --locked --version "0.6.0"

      - name: CI
        run: make test
